### ISSUE TITLE
Creating CSCMatrix from SparseVector throws ArrayIndexOutOfBondException when the active size is a power of 2

### ISSUE THREAD

**Issue by quentinms** [scalanlp/breeze#320]
I have the following snippet 

```scala
for (fill ← 0 until 2000) {
    
  val vb = new VectorBuilder[Int](421337)
    
  for (i ← 0 to fill) {
    vb.add(i,i)
  }
    
  val sv = vb.toSparseVector
    
  try{
    sv.asCSCMatrix()
  } catch {
    case t: Throwable => println("It crashed for: "+sv.activeSize)
  }
}
```

Which gives me this output:

It crashed for: 1
It crashed for: 2
It crashed for: 4
It crashed for: 8
It crashed for: 16
It crashed for: 32
It crashed for: 64
It crashed for: 128
It crashed for: 256
It crashed for: 512
It crashed for: 1024

I tried looking at the source but I'm not familiar enough with it to understand what causes this.

I am using scala 2.10.4 and Breeze 0.10

The complete error is:

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at breeze.linalg.SparseVector$mcI$sp$$anonfun$4.apply$mcII$sp(SparseVector.scala:159)
	at breeze.linalg.SparseVector$mcI$sp$$anonfun$4.apply(SparseVector.scala:158)
	at breeze.linalg.SparseVector$mcI$sp$$anonfun$4.apply(SparseVector.scala:158)
	at scala.Array$.tabulate(Array.scala:331)
	at breeze.linalg.SparseVector$mcI$sp.asCSCMatrix$mcI$sp(SparseVector.scala:158)
	at XXX.tests$$anonfun$1.apply(tests.scala:17)
	at XXX.tests$$anonfun$1.apply(tests.scala:7)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at XXX.tests$delayedInit$body.apply(tests.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at XXX.tests$.main(tests.scala:5)
	at XXX.tests.main(tests.scala)
```

**Comment by mikeunwin** [comment]
Hi all, did this ever get patched?

**Comment by dlwh** [comment]
nope. @gabeos ??

**Comment by dlwh** [comment]
apparently already fixed...
