### ISSUE TITLE
MatrixNotSymmetricException is too sensitive

### ISSUE THREAD

**Issue by pkge** [scalanlp/breeze#356]
I'm getting a "Matrix is not symmetric" error on matrices that in theory should be symmetric but aren't exactly. It looks like a floating point precision issue on the symmetry test.

This code throws the error:

```scala

import breeze.linalg._
import breeze.stats.distributions.MultivariateGaussian

// initialise some vector and matrices
val n = 3
val q = DenseVector.rand[Double](n)
val A = DenseMatrix.eye[Double](n) + q * q.t
val B = inv(A)
val u = DenseVector.zeros[Double](n)

// this throws the error
val D = MultivariateGaussian(u, B)

```

And the result:

```
breeze.linalg.MatrixNotSymmetricException: Matrix is not symmetric
	at breeze.linalg.package$$anonfun$requireSymmetricMatrix$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(package.scala:120)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at breeze.linalg.package$$anonfun$requireSymmetricMatrix$1.apply$mcVI$sp(package.scala:118)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at breeze.linalg.package$.requireSymmetricMatrix(package.scala:118)
	at breeze.linalg.cholesky$ImplCholesky_DM$.apply(cholesky.scala:25)
	at breeze.linalg.cholesky$ImplCholesky_DM$.apply(cholesky.scala:16)
	at breeze.generic.UFunc$class.apply(UFunc.scala:48)
	at breeze.linalg.cholesky$.apply(cholesky.scala:15)
	at breeze.stats.distributions.MultivariateGaussian.<init>(MultivariateGaussian.scala:38)
    ...
```

**Comment by dlwh** [comment]
Obviously this should be fixed. In the meantime you can symmetrize it yourself.

**Comment by gabeos** [comment]
Started to work on this. Got a little sidetracked into making a generic (for Float, Double, Int, Long) randNum[V], but I made it a relative epsilon check with eps = 1E-15 * max(a,b) which seems to work decently well. Constant was copied from apache.commons.math3 Cholesky.

Will submit in a patch later this week.

**Comment by pkge** [comment]
Yeah, for now I'm working around it, but looking forward to the patch. Thanks!

**Comment by xjw** [comment]
Any update on this patch? Look forward to the fix.

**Comment by rustandruin** [comment]
Also have the same issue with a matrix B that I know is symmetric by construction, and for which the top singular value of B - B.t according to Breeze's own svd is 0 to at least 12 decimal places. 

I'm new to Breeze, and Scala in general, but it seems like this is a case where it's best to throw a warning and let the user proceed rather than fix an arbitrary limit on how non-symmetric the matrix can be before failing.

**Comment by dlwh** [comment]
i'll fix it this weekend. I just waited on the promised fix from @gabeos,
but I'll knock it out.
