### ISSUE TITLE
Is there any bugs to divide a sparse vector with `:/` at v0.11.1?

### ISSUE THREAD

**Issue by yu-iskw** [scalanlp/breeze#382]
Hi all, 

I tried to divide a sparse vector by a scalar value with `:/`, I got a wrong result.
Is there any bugs to divide a sparse vector at v0.11.1, if the vector has any zero values?

I tried to run the below test code. And you can get it in [yu-iskw/breeze at test-v0.11.1](https://github.com/yu-iskw/breeze/tree/test-v0.11.1). I only added the simple test code [Add a test for dividing a sparse vector machine · 989a288 · yu-iskw/breeze](https://github.com/yu-iskw/breeze/commit/989a28809bec21b429e43b1679f1fb832d073cb7).
```
  test("dividing a sparse vector") {
    val vec = SparseVector(5)(0 -> 0.0, 3 -> 60.0, 4 -> 80.0)
    val n = 60.0
    val answer1 = vec :/ n
    val answer2 = vec.toDenseVector :/ n
    assert(answer1.toDenseVector === answer2)
  }
```

As a result of `sbt clean test`, I got the error. The `answer1` seems to be a zero vector.
Although I checked the same code on v0.10, there is no problems.
```
[info] - dividing a sparse vector *** FAILED *** (226 milliseconds)
[info]   DenseVector(0.0, 0.0, 0.0, 0.0, 0.0) did not equal DenseVector(0.0, 0.0, 0.0, 1.0, 1.3333333333333333) (SparseVectorTest.scala:350)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:498)
[info]   at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1559)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:416)
[info]   at breeze.linalg.SparseVectorTest$$anonfun$41.apply$mcV$sp(SparseVectorTest.scala:350)
[info]   at breeze.linalg.SparseVectorTest$$anonfun$41.apply(SparseVectorTest.scala:342)
[info]   at breeze.linalg.SparseVectorTest$$anonfun$41.apply(SparseVectorTest.scala:342)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[info]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1559)
[info]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
[info]   at org.scalatest.FunSuite.runTest(FunSuite.scala:1559)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[info]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
[info]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1559)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[info]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1559)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[info]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
[info]   at org.scalatest.FunSuite.run(FunSuite.scala:1559)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:84)
[info]   at sbt.TestRunner.run(TestFramework.scala:94)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFunction.apply(TestFramework.scala:224)
[info]   at sbt.Tests$$anonfun$7.apply(Tests.scala:196)
[info]   at sbt.Tests$$anonfun$7.apply(Tests.scala:196)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]   at sbt.Execute.work(Execute.scala:244)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]   at java.lang.Thread.run(Thread.java:745)
```

Thanks,

**Comment by dlwh** [comment]
Sigh, I thought I tested that change better than this. I'll get this fixed
quickly.

**Comment by yu-iskw** [comment]
@dlwh, thank you for your quick response. Because Apache Spark 1.3.0 depends on breeze v0.11.1, I'll share the bug with the Spark community.
Thank you for your great work.

**Comment by dlwh** [comment]
publishing 0.12-SNAPSHOT artifacts now. let me know if they're fine and
I'll cut 0.11.2

**Comment by yu-iskw** [comment]
Sorry for the delay in replying. I moved from Tokyo to New York in order to attend Spark Summit East.
I verified the snapshot and the difference.
https://github.com/scalanlp/breeze/commit/f61d2f61137807651fc860404a244640e213f6d3

I appreciate your great work and support.

**Comment by yu-iskw** [comment]
Hi @dlwh, sorry, I know you must be busy. When is the next version released?

**Comment by yu-iskw** [comment]
@dlwh, thank you for your great support! I'll try to upgrade the breeze version from 0.11.1 to 0.11.2 in Spark. Thanks.
