### ISSUE TITLE
CSCMatrix constantly out of heap space Despite large XMX

### ISSUE THREAD

**Issue by asevans48** [scalanlp/breeze#513]
I have been fiddling with -Xmx and other values such as UseConcMarkSweep. My current matrix is 50,000 rows \* 1000 columns and is 33 % full. This is quite reasonable for my small projects where I have 1000 documents and use the hashing trick to generate a matrix.

While Universal Java Matrix Package,BidMach, and MTJ can calculate these matrices, they are quite slow to do so. Numpy is actually blazingly fast at this. However, I am receiving an out of memory error in the ArrayBuilder class, particularly in the attempt to add to the Long in the add function at line 458.

This feels somewhat like a serious problem as most matrix libraries are actually capable of handling this code. Is there any plan to improve memory usage?

```
val a = new CSCMatrix.Builder[Double](rows = 50000,cols = 1000)
      while(a.activeSize < 50000000 *.33){
        a.add(Random.nextInt(50000), Random.nextInt(1000), Random.nextDouble())
      }
      val mat  = a.result
      val t = System.currentTimeMillis()
      println("Test Started")
      mat * mat.t

      println("TEST TOOK: %d".format(System.currentTimeMillis()  - t))  
      println("Test Complete")
```

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at scala.collection.mutable.ArrayBuilder$ofDouble.mkArray(ArrayBuilder.scala:518)
    at scala.collection.mutable.ArrayBuilder$ofDouble.resize(ArrayBuilder.scala:524)
    at scala.collection.mutable.ArrayBuilder$ofDouble.ensureSize(ArrayBuilder.scala:536)
    at scala.collection.mutable.ArrayBuilder$ofDouble.$plus$eq(ArrayBuilder.scala:541)
    at scala.collection.mutable.ArrayBuilder$ofDouble.$plus$eq(ArrayBuilder.scala:511)
    at breeze.linalg.CSCMatrix$Builder$mcD$sp.add$mcD$sp(CSCMatrix.scala:457)
    at breeze.linalg.operators.CSCMatrixOps$$anon$97.apply(CSCMatrixOps.scala:715)
    at breeze.linalg.operators.CSCMatrixOps$$anon$97.apply(CSCMatrixOps.scala:692)
    at breeze.linalg.ImmutableNumericOps$class.$times(NumericOps.scala:135)
    at breeze.linalg.CSCMatrix.$times(CSCMatrix.scala:41)
    at com.hygenics.matrixtests.Driver$.main(Driver.scala:22)
    at com.hygenics.matrixtests.Driver.main(Driver.scala)
`

**Comment by dlwh** [comment]
I'll take a look at this this weekend

**Comment by dlwh** [comment]
it's a non-trivial fix. I can't promise a timeline on this

**Comment by asevans48** [comment]
Ok. I'll check back periodically.

**Comment by asevans48** [comment]
Any chance at a fix?

**Comment by dlwh** [comment]
sorry, i'm swamped with work right now. i took a look a while back and it
wasn't immediately obvious, so i had to shelve it for now.

**Comment by dlwh** [comment]
So, Breeze just can't represent matrices with row * cols > Int.MaxValue. It's a design flaw that I'm not going to fix before a major redesign.  I definitely don't understand the assertion that it works with BidMat (https://github.com/BIDData/BIDMat/blob/master/src/main/scala/BIDMat/SMat.scala#L281), since your test will overflow its nnz calculation w.h.p., which should cause it to throw around line 299.

As part of this exercise I improved the matrix multiply algorithm substantially, but it's still not going to work with your example.
