### ISSUE TITLE
argtopk failed when applying to DenseVector and k == length of vector

### ISSUE THREAD

**Issue by yanboliang** [scalanlp/breeze#561]
```argtopk``` failed when applying to ```DenseVector``` and ```k == length of vector```. The 0.12 release introduced this bug.
```
val topicCounts = DenseVector(Array(1.29, 4.89, 0.8, 1.8, 2.5, 0.3))
val topIndices = argtopk(topicCounts, 6)
println(topIndices.toArray.mkString(","))
```
It throws exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Invalid position specification: 6 with coll length: 6
	at scala.Predef$.require(Predef.scala:224)
	at breeze.util.quickSelect$$anon$5.implQuickSelectSort$5(Selecting.scala:103)
	at breeze.util.quickSelect$$anon$5.apply$mcI$sp(Selecting.scala:137)
	at breeze.linalg.argtopk$$anon$5.apply(argsort.scala:40)
	at breeze.linalg.argtopk$$anon$5.apply(argsort.scala:36)
	at breeze.generic.UFunc$class.apply(UFunc.scala:53)
	at breeze.linalg.argtopk$.apply(argsort.scala:33)
```

**Comment by yanboliang** [comment]
Send PR #562 to fix this bug.

**Comment by yanboliang** [comment]
#562 fix this bug, so close this issue.
