### ISSUE TITLE
CSCMatrix and concurrent updates

### ISSUE THREAD

**Issue by carschno** [scalanlp/breeze#576]
I have the following code working fine:

    val vectors: Seq[SparseVector[Double]] = ...
    vectors
      .foreach(v => add(deltas, v, computeWinner(v.toDenseVector)))

The method `add` is implemented as follows, updating a CSCMatrix by element-wise in-place addition with a (column) vector:

    def add(m: Matrix[Double], v: Vector[Double], col: Int): Unit = {
      v.activeIterator.foreach {
        case (row: Int, value: Double) => m.update(row, col, value)
      }
    }

This works perfectly fine, so I've tried to parallelize the process by changing the initial vector sequence into a parallel sequence:

    vectors
      .par
      .foreach(v => add(deltas, v, computeWinner(v.toDenseVector)))

The result is that I get `ArrayIndexOutOfBoundsException`s and `IllegalArgumentException`s like the following:

    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
  	  at java.lang.System.arraycopy(Native Method)
	  at breeze.linalg.CSCMatrix.update(CSCMatrix.scala:102)
	  at breeze.linalg.CSCMatrix.update$mcD$sp(CSCMatrix.scala:76)
          [...]

and

    Exception in thread "main" java.lang.IllegalArgumentException: fromIndex(761) > toIndex(760)
	  at java.util.Arrays.rangeCheck(Arrays.java:113)
	  at java.util.Arrays.binarySearch(Arrays.java:1901)
	  at breeze.linalg.CSCMatrix.breeze$linalg$CSCMatrix$$locate(CSCMatrix.scala:151)
	  at breeze.linalg.CSCMatrix.update(CSCMatrix.scala:79)
	  at breeze.linalg.CSCMatrix.update$mcD$sp(CSCMatrix.scala:76)
      [...]

Due to parallelization it is very hard to track down the specific elements which cause the problem, but it is very clear that the root links to the parallelization.

**Comment by dlwh** [comment]
CSCMatrix doesn't work with concurrent updates. That's just how it's
designed.
