### ISSUE TITLE
IllegalArgumentException when using left division

### ISSUE THREAD

**Issue by ethanluoyc** [scalanlp/breeze#620]
I am solving a large system of equations of the form Ax = b. In MATLAB, to obtain the least square solution to x you can find it by A \ b. I tried to do the same thing with Breeze. However, it gives me the following exception (Using breeze_2.10 and breeze-natives_2.11, on macOS):

```
Jan 22, 2017 9:14:44 PM com.github.fommil.jni.JniLoader liberalLoad
INFO: successfully loaded /var/folders/yj/9p4v99md68l9lwnw0bqgk3mm0000gn/T/jniloader2328579485951715374netlib-native_system-osx-x86_64.jnilib
Exception in thread "main" java.lang.IllegalArgumentException
	at breeze.linalg.operators.DenseMatrixMultiplyStuff$implOpSolveMatrixBy_DMD_DMD_eq_DMD$.QRSolve(DenseMatrixOps.scala:216)
	at breeze.linalg.operators.DenseMatrixMultiplyStuff$implOpSolveMatrixBy_DMD_DMD_eq_DMD$.apply(DenseMatrixOps.scala:140)
	at breeze.linalg.operators.DenseMatrixMultiplyStuff$implOpSolveMatrixBy_DMD_DMD_eq_DMD$.apply(DenseMatrixOps.scala:123)
	at breeze.linalg.ImmutableNumericOps$class.$bslash(NumericOps.scala:144)
	at breeze.linalg.DenseMatrix.$bslash(DenseMatrix.scala:52)
	at breeze.linalg.operators.DenseMatrixMultiplyStuff$implOpSolveMatrixBy_DMD_DVD_eq_DVD$.apply(DenseMatrixOps.scala:229)
	at breeze.linalg.operators.DenseMatrixMultiplyStuff$implOpSolveMatrixBy_DMD_DVD_eq_DVD$.apply(DenseMatrixOps.scala:226)
	at breeze.linalg.ImmutableNumericOps$class.$bslash(NumericOps.scala:144)
	at breeze.linalg.DenseMatrix.$bslash(DenseMatrix.scala:52)
	at TestRun$.main(TestRun.scala:23)
	at TestRun.main(TestRun.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
** On entry to DGELS , parameter number  6 had an illegal value
** On entry to DGELS , parameter number  6 had an illegal value
```

I managed to pin down the problem with the following example and sample data.
```scala
object TestRun {

  import java.io.File

  import breeze.linalg._

  def main(args: Array[String]): Unit = {
    val numData = 35603
    val numFeatures = 445

    val W = csvread(new File("weights.csv"))
    val y = csvread(new File("values.csv"))

    val arr = W.toArray

    var bMeanWeights: DenseMatrix[Double] = new DenseMatrix(1, numData * numFeatures, arr)
    bMeanWeights = bMeanWeights.reshape(numFeatures, numData).t
    val bMeanWeightsCopy = bMeanWeights.copy

    var bMeanValues = y.toDenseVector

    val result = bMeanWeights \ bMeanValues // Using bMeanWeights will result in error, however, replacing it with a copy (i.e. bMeanWeightsCopy) the program will run as normally.


  }
}
```

However, I am not able to narrow the bug further. My doubt is that something went wrong in either `reshape` or `t`.

[data.zip](https://github.com/scalanlp/breeze/files/722271/data.zip)

**Update**
I found this. 

http://www.netlib.org/lapack/lapack-3.1.1/html/dgels.f.html

It looks like the solver uses the isTranspose information and pass that to the DGELS routine. However I wonder if this is the desired behavior? When I have Ax = B and I compute A \ B, I do not care if A is tranpose in its representation or not. However, `\` seems to be using that information to call the DGELS routine. As seen in https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/linalg/operators/DenseMatrixOps.scala#L208

**Comment by dlwh** [comment]
yeah, i'm sure it's just a configuration problem in how we setup the call.
i will look into it.

**Comment by nemppu** [comment]
I'm having the same issue. I needed to take a transpose `A = coefficients.t` to create the coefficient matrix for `Ax = b`. Copying the transposed matrix (`A = coefficients.t.copy`) resets isTranspose, and seems to resolve the issue. At least then `A \ b` works for my use case.
