### ISSUE TITLE
LogNormalTest failure (seen in Scala 2.11 community build)

### ISSUE THREAD

**Issue by SethTisue** [scalanlp/breeze#629]
seen at https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/349/consoleFull :

```
[breeze] [info] - probability gets the same fraction of things as the sampler *** FAILED *** (295 milliseconds)
[breeze] [info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[breeze] [info]    (HasCdfTestBase.scala:35)
[breeze] [info]     Falsified after 87 successful property evaluations.
[breeze] [info]     Location: (HasCdfTestBase.scala:35)
[breeze] [info]     Occurred when passed generated values (
[breeze] [info]       arg0 = LogNormal(0.0,0.1)
[breeze] [info]     )
[breeze] [info]   org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException:
[breeze] [info]   at org.scalatest.prop.Checkers$.doCheck(Checkers.scala:402)
[breeze] [info]   at org.scalatest.prop.Checkers$class.check(Checkers.scala:346)
[breeze] [info]   at breeze.stats.distributions.LogNormalTest.check(LogNormalTest.scala:27)
[breeze] [info]   at org.scalatest.prop.Checkers$class.check(Checkers.scala:357)
[breeze] [info]   at breeze.stats.distributions.LogNormalTest.check(LogNormalTest.scala:27)
[breeze] [info]   at breeze.stats.distributions.HasCdfTestBase$$anonfun$1.apply$mcV$sp(HasCdfTestBase.scala:35)
[breeze] [info]   at breeze.stats.distributions.HasCdfTestBase$$anonfun$1.apply(HasCdfTestBase.scala:35)
[breeze] [info]   at breeze.stats.distributions.HasCdfTestBase$$anonfun$1.apply(HasCdfTestBase.scala:35)
[breeze] [info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```

**Comment by SethTisue** [comment]
green in run 350, so apparently an intermittent problem

**Comment by SethTisue** [comment]
closing this ticket, as the 2.11 community build is using an old branch of breeze. if we ever see this error in the 2.12 build, which is tracking master, we could reopen
