### ISSUE TITLE
viz: update JFree dependencies

### ISSUE THREAD

**Issue by hmf** [scalanlp/breeze#750]
Besides breeze I also have code that depends on JFree chart. I updated this to the latest 1.5.0. Any way Viz can also be updated to 1.5.0? This is because I get the error:

```
[error] Uncaught exception when running pt.inescn.dsp.AudioSpec: java.lang.NoSuchMethodError: org.jfree.chart.JFreeChart.setPadding(Lorg/jfree/ui/RectangleInsets;)V
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: org.jfree.chart.JFreeChart.setPadding(Lorg/jfree/ui/RectangleInsets;)V
[error] 	at breeze.plot.Plot.chart$lzycompute(Plot.scala:199)
[error] 	at breeze.plot.Plot.chart(Plot.scala:196)
[error] 	at breeze.plot.Plot.title_$eq(Plot.scala:129)
```
TIA

**Comment by philwalk** [comment]
I'm in the same situation.
