### ISSUE TITLE
Cannot create vectors

### ISSUE THREAD

**Issue by heywrcoding** [scalanlp/breeze#756]
// My codes:
    val myList = Array\[Double\](1.9, 2.9, 3.4, 3.5)
    val dv = new DenseVector\[Double\](myList)
    println(dv)

// Compiler logs：
Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.mutable.HashMap$.apply(Lscala/collection/Seq;)Lscala/collection/GenMap;
	at breeze.generic.MMRegistry2$class.$init$(Multimethod.scala:184)
	at breeze.linalg.operators.DenseVectorOps$$anon$1.<init>(DenseVectorOps.scala:22)
	at breeze.linalg.operators.DenseVectorOps$class.$init$(DenseVectorOps.scala:22)
	at breeze.linalg.DenseVector$.<init>(DenseVector.scala:225)
	at breeze.linalg.DenseVector$.<clinit>(DenseVector.scala)
	at breeze.linalg.DenseVector.<init>(DenseVector.scala:63)
	at breeze.linalg.DenseVector$mcD$sp.<init>(DenseVector.scala:50)
	at breeze.linalg.DenseVector$mcD$sp.<init>(DenseVector.scala:55)
	at UnitTest$.main(UnitTest.scala:21)
	at UnitTest.main(UnitTest.scala)

//Scala version: scala-sdk-2.13.0
//JDK version: 1.8.0
//Using IDEA

**Comment by dlwh** [comment]
sorry for slow response. If you're seeing this, I think you're probably mixing scala versions
